blank_issues_enabled: true
contact_links:
  - name: Все Issues
    url: https://github.com/RaijiTRW/Empyrion-Galactic-Survival-Reforged-Eden-2-RU/issues
    about: Откройте общий список проблем и предложений.

